
TOP = ../../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

ARCHIVE += sioc-gunb-ssa01.archive
ARCHIVE += sioc-l2b-ssa03.archive
ARCHIVE += sioc-l3b-ssa01.archive

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

# End of File

