
TOP = ../../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

ARCHIVE += $(IOCADMIN)/archive/archive_iocAdmin.archive

# Install archive list into $TOP/archive
ARCHIVE += ssa_CA1300.tpl-arch
ARCHIVE += ssa_CA186.tpl-arch
ARCHIVE += ssa_CA186_module.tpl-arch

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

# End of File

